### PR TITLE
more enhacements 

### PR DESCRIPTION
**Pull request by shime**
Main improvements:
- super fast tests
- include Guard
- gem updates and checks for duplicates
- support for platform dependent versions

I hope it's good to merge!

### CODE REVIEW

**Comment by DruRly** [comment]
Looks great so far! :metal: In the process of reviewing

**Comment by mivanek** [comment]
I'm a little late to the party, but here are some of the changes I've implemented in this pull request:
- Check for newer versions of added gems, in cooperation with @shime 
- Start using OptionParser library for parsing options
- Convert -g/--gemfile flag to use OptionParser
- Implement --no-version, --no-install, --version and -v flags
- Implement tests for covering newly implemented flags

I'm currently working on implementing --environment flag so you can specify which environment you want to add the gem to. It should have support for multiple environments as well. I hope I'll be done some time in the next two days, maybe even today. Hope you're satisfied with the changes so far, if you have any comments, please let me now.

**Comment by shime** [comment]
:+1: :+1: :punch: :boom: :metal:

**Comment by DruRly** [comment]
I noticed that when detecting whether a gem already exists in the Gemfile, it does not recognize gems which do not have a version.

Steps to replicate:
1. Start with a Gemfile that includes `sidekiq` without a version number.
2. Run `gemrat sidekiq`
3. You receive:
   #=> gem `sidekiq`, `2.12.4` added to your Gemfile.
   #=> Bunlding...

Version bumping and update confirmations work great!

This is still good to accept. Just noticed this and would like to get around to it at some point. Still testing. Thanks again guys!

**Comment by mivanek** [comment]
Thanks for the heads up. I was just talking to @shime earlier today and we realized that there are some edge cases/situations that we probably haven't covered too well, and I guess this is one of them. We've also realized that implementing the -e/--environment flag might take up more time than we anticipated because there are a couple of variations we need to cover that we haven't originally thought of, so it might take us a couple of days more than what I have anticipated earlier. Either way, we'll try to cover all that we can think of in the next pull request. If you think of or find any other bug/edge case that we maybe haven't noticed, please let us know. These things can easily go under the radar.

Cheers. :beer:

**Comment by DruRly** [comment]
Thanks for the update @mivanek. There's also a failing test which targets the -e/--environment flag functionality that you just mentioned. I don't think you intended for this to be in the pull. Would guys like for me to remove this and merge or edit the pull yourselves?

**Comment by mivanek** [comment]
You can remove the test and merge if you want to. I think I've also let a require 'pry' in gemrat.rb slip through, so you can remove that as well, if you haven't already.

**Comment by DruRly** [comment]
I changed the test to pending and merged. It's released as v0.4.0 and tagged. Added you to authors. Thanks again!

**Comment by shime** [comment]
:sunglasses:

**Pull request merged**
