### PR TITLE
Tiny changes

### PR DESCRIPTION
**Pull request by moonglum**
Just a few tiny things I noticed while starting to read your code :smile: 
- Bundler is actually a runtime dependency: It was marked as a development dependency
- Set the versions of the dependencies
- Call `Bundler::CLI.start([])` instead of shelling out

### CODE REVIEW

**Comment by DruRly** [comment]
Thanks for the pull @moonglum! Regarding #d2bb608, I actually don't think it's a good idea to use specific versions for gems. http://bundler.io/rationale.html#faq-1 (From @shime) 

Gem dependencies should "play nice" with whatever version is being used in a project, when possible.

Sorry for giving you the impression that I think it's a good idea to always lock gem versions down. I think it's more nuanced. 

Gems are meant to be used across projects, therefore, versions used should be loose as possible. 

I'll revisit the others soon but the locking down of versions stuck out to me.

**Comment by moonglum** [comment]
Ok, then I totally misunderstood you. I personally prefer `~>`, too :smile: Should I change it in the pull request?

**Comment by DruRly** [comment]
Great catch by realizing that `bundler` is a runtime dependency in this context but I wouldn't specify any versions unless someone raises an issue. I think we should leave `gemrat` as flexible as possible.

We depend on `colored`'s ability to color text and `bundler`'s ability to bundle. If these features were knocked out in some version or introduced at some earlier version then we should set the marker on those. But these are pretty basic things. If we had lots of external dependencies, there would definitely be cases where we would want to lock some things down.

It's much of the same case for development dependencies. If someone raises an issue, I think we should wrangle versions but until then let's stay flexible. 

I would keep the `bundler` move to runtime dependencies and drop the versions. Thanks again @moonglum. Great catch :+1:

**Comment by moonglum** [comment]
I rebased on your master after the pull request and adjusted the dependencies :smile:

**Comment by DruRly** [comment]
This breaks when bundling. I think the issue is that you don't require `bundler` although you attempt to use `Bundler::CLI`

**Comment by DruRly** [comment]
Unaddressed breaking merge.

**Pull request closed without merging**
