### PR TITLE
Do not add gem if it already exists

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
there is a feature request on reddit - `gemrat <group> <gem>`
i could implement it if you are interested

**Comment by DruRly** [comment]
Thanks for the pull. Could you add some tests?

**Comment by ghost** [comment]
mm, actually i updated gemrat_spec.rb with a new spec

**Comment by DruRly** [comment]
Ahhh I see. Sorry about that. I'll review it. Thanks!

**Comment by moonglum** [comment]
I think it would be even nicer, if it would update the version of the bundled gem if it's already in there:

> Gem 'sinatra' already installed in version 1.4.2
> Found 1.4.3 on Rubygems, updated in your Gemfile

...and just ignore it, if it's the same version :smile:

**Comment by DruRly** [comment]
@moonglum I like your suggestion. It communicates exactly what's going on. Having a confirmation step would also be nice. Confirming that the developer would indeed like to update the existing gem. She/he may not know that it's already there.

**Comment by moonglum** [comment]
Yep :+1:

**Comment by DruRly** [comment]
This has been added in https://github.com/DruRly/gemrat/pull/12. Along with update confirmations :grinning:

**Comment by moonglum** [comment]
Awesome :milky_way:

**Pull request closed without merging**
